### ISSUE TITLE
Issue with map Port Town 2

### ISSUE THREAD

**Issue by ghost** [WarzoneMC/Maps#102]
Beacons are needed to indicate monument locations

*This issue was submitted through our issue submission tool.*

**Comment by JapaneseSquid** [comment]
Beacons aren’t obligatory to indicate monument locations.
Besides, it’s a DTM so the beacon will be off centered, not to mention there is water underneath that shouldn’t be replaced by the beacon blocks
This map isn’t in the current rot so it’s not needed, and if it’s added people will play it enough to remember
