### ISSUE TITLE
TechnoWar Silverfish blocks

### ISSUE THREAD

**Issue by BTKingly** [WarzoneMC/Maps#125]
While playing this map, I noticed a couple of silverfish in the tunnels below the map. I assume that they were spawned once their "egg" block was broken, but I couldn't tell you what type of block it was. Might be worth just world editing them away.

For reference: https://github.com/WarzoneMC/Maps/tree/master/CTW/TechnoWar

**Comment by CrazyisCreeps** [comment]
I believe the egg blocks are intended to be there, they appear to block up some of the tunnels originally. Perhaps limiting the amount would do some good, I think there's about 10 per section?
