### ISSUE TITLE
CTW Wool Placement

### ISSUE THREAD

**Issue by TBGameeer** [WarzoneMC/Maps#14]
In the CTW maps, Deepwind and Outback, you can place the wool as you grab it throughout the spawn, middle islands and your own team's spawn.

 I believe this feature should be removed and that wool should only be place-able in the correct spot (behind the spawn in Deepwind, at the side of the spawn in Outback) because a player can just grab a stack of wool from the infinitively restocking chests and go placing wool as he goes back to his spawn. 

If he dies, and he placed wool in his spawn island, he can just go back and mine it from there to go place it. It is a very easy way to win since you dont have to go back to the wool area/building, which I think breaks the purpose of the game.

**Comment by tjhubz** [comment]
Should be in main warzone section, not maps
