### ISSUE TITLE
Mayan Apocalypse Spawns

### ISSUE THREAD

**Issue by BTKingly** [WarzoneMC/Maps#260]
Spawns seem to be above void, resulting in players dying upon each re-spawn

**Comment by JapaneseSquid** [comment]
quick note for the other brother it’s a pruning issue and not a spawn location issue I believe

**Comment by BTKingly** [comment]
Probably. I was too lazy to look into it

**Comment by JapaneseSquid** [comment]
Understandable feeling

**Comment by CrazyisCreeps** [comment]
Damm there's enough pruning issues
