### ISSUE TITLE
Race For Victory 2 (Map Bug)

### ISSUE THREAD

**Issue by Synconix** [WarzoneMC/Maps#41]
Has anyone else seen that on the map Race For Victory 2 sometimes it glitches and you can enter your own wool. Seeing how it's CTW there are wool and only the other team can enter to take the wool. Ya know what I mean? But sometimes I have seen it glitch and a team can enter their own wool. Not sure if this is an issue for other maps but I have noticed it a lot on this 1 map.

**Comment by Palmidence** [comment]
https://github.com/WarzoneMC/Maps/pull/42 should fix this.

**Comment by Synconix** [comment]
Yea, it's been a bug since the release
