### ISSUE TITLE
Map kinda glitch that makes your team immortal

### ISSUE THREAD

**Issue by MarginPankam** [WarzoneMC/Maps#79]
The problem is on the WarlockDTM map. On the map has some gunpowder and sand, you can make TNT and blow up your own wool but the TNT explosion isn't counted as player damage to the wool. So you can blow up your own wool and never lose on that map because you don't have any wool for enemies to break.

**Comment by BennyDoesTheStuff** [comment]
That's not good, it's a bit late for me right now so tomorrow I'll look into it and push a change to fix this.
