### ISSUE TITLE
Repairing Broken OP Bow to full durability glitch

### ISSUE THREAD

**Issue by MarginPankam** [WarzoneMC/Maps#89]
This glitch is on map Aerial Conquest where there are some chest filled with Power 2 bows but they're almost broken. You can mine iron, make an anvil, and repair the Power 2 bow with your spawn-kit normal bow. It costs xp but the xp bar is your level bar, so it consumes no xp to repair the bow. I think that this glitch can appear in other maps that have some iron, broken OP gears, and a spawn-kit pick.

**Comment by JapaneseSquid** [comment]
Not a glitch, just a game feature that can be abused quite easily. I did this all the time on aerial conquest, even with the diamond sword bank when it had diamond blocks.

**Comment by MarginPankam** [comment]
Should make anvil uncraftable
