### ISSUE TITLE
A glitch with wool registration on the map Arctic v2

### ISSUE THREAD

**Issue by dependants** [WarzoneMC/Maps#90]
## Expected Behaviour

Breaking a piece of wool registers as a single broken wool.

## Actual Behaviour

On the map Arctic v2, there tends to be situations where breaking a piece of wool will not add towards completing the objective. Meaning that breaking the wool does nothing.

## Steps to reproduce the behaviour

I'm not completely sure what the actual cause of this problem is. 

### Additional Comments

Other players are able to break the wool and complete the objective whilst the person with the glitch is unable to support it.

**Comment by tjhubz** [comment]
This is not a glitch with the plugin, but rather a glitch with a specific map.json. Figure out which map has this issue please and make a new issue.
